### PR TITLE
:wrench: :arrow_up:  fix optiongroup header + bump version

### PR DESCRIPTION
**Pull request by the-j0k3r**
Before

before-fix

After

after-fix

I had to really really fight my OCD, your code has these really long selector lines that go on until infinity
I would like to wrap them at around a more manageable size on another PR.

It would make also things line up inside Stylus and be more human readable.

What say you?

### CODE REVIEW

**Comment by RaitaroH** [comment]
If it really bothers you that I don't wrap the selectors than feel free to wrap them.

**Comment by the-j0k3r** [comment]
> If it really bothers you that I don't wrap the selectors than feel free to wrap them

:) It will be more pretty and easier youll see ;)

**Comment by RaitaroH** [comment]
> :) It will be more pretty and easier youll see ;)

**Comment by the-j0k3r** [comment]
Ive added cursor width and color, expect a PR in a few.

**Pull request merged**
