### PR TITLE
:new: :arrow_up: add cursor width and color option + bump version

### PR DESCRIPTION
**Pull request by the-j0k3r**
Comes in handy to people who find the default 1px wide hard to see.

cursor-width

Do you know if its possible to have spinboxes instead of drop down options for the width?

### CODE REVIEW

**Comment by RaitaroH** [comment]
`Do you know if its possible to have spinboxes instead of drop down options for the width?` 
No idea.

@Mottie Do you know?

**Comment by RaitaroH** [comment]
@the-j0k3r 
```
Style code has an error - parse error on value ";" (SEMI) 
on line 177 around "rWidth]]*/; --cursor-c". 
If you need help, post a new discussion 
at https://forum.userstyles.org/post/discussion/5 .
```
God damn userstyles... what? I am not even sure what there is to fix :man_facepalming: 

Also dude, I added you as a collab. Leave me alone :stuck_out_tongue_winking_eye:

**Comment by the-j0k3r** [comment]
> Also dude, I added you as a collab. Leave me alone stuck_out_tongue_winking_eye

Thanks :) Maybe.

No sure about the error though.... Weird.

**Comment by the-j0k3r** [comment]
```
Style code has an error - parse error on value ";" (SEMI)
on line 177 around "rWidth]]*/; --cursor-c".
If you need help, post a new discussion
at https://forum.userstyles.org/post/discussion/5 .
```
@RaitaroH  When you submitted this did you add the advanced configuration options for the cursor width and color? Just a thought on reason of error.

**Comment by RaitaroH** [comment]
`configuration options for the cursor width and color`
Could have helped to do that :man_facepalming:

**Pull request merged**
