### PR TITLE
fix search(ing) somewhat.

### PR DESCRIPTION
**Pull request by the-j0k3r**
I had to revert my previous attempt in a66c204 because it brought to light something I dont yet understand and partly because the implementation was incomplete,

searching

Im looking into fixing #21 before merging this

### CODE REVIEW

**Comment by RaitaroH** [comment]
XD This was on my to do list, but I never came around to do it. ALSO OMG DUDE in the morning I always have like 10 emails all with your activity.

**Comment by the-j0k3r** [comment]
>ALSO OMG DUDE in the morning I always have like 10 emails all with your activity.

I disabled email notifications a long ago its easier/cleaner to use GitHub web notifications only. I guess that only works if you care about your repos and open a GitHub tab.

ALSO OMG stop complaining. :grin: 

>This was on my to do list,

You *actually* have a todo list? :grinning: 

While were complaining about random stuff, ALSO OMG WTH is it with reacting to your own posts?

**Comment by RaitaroH** [comment]
> You actually have a todo list?

Pff... I have went through hundreds of pages of complicate engineering crap in the last week and a spit (exams... bloody exams). So OMG imagine that my styles are on the back burner :grimacing: 

I will be busy even after my exams :sob:

**Comment by the-j0k3r** [comment]
> I will be busy even after my exams sob

Look at that -><kbd> </kbd><- its the worlds smallest fiddle playing a sad song just for you. :)

**Comment by RaitaroH** [comment]
Not sure if you try to be funny, or cringe.

**Comment by the-j0k3r** [comment]
You never heard heard that expression? Around these parts when someone complains and cries about something, thats usually the reply, some people use fiddle others violin. 

I only used it cause your whining made me cringe. :) SO I thought Ide play a tune for you.

I guess I should have asked where youre from before. :)

**Pull request merged**
